[package]
name = "avior-infuser-rust"
version = "0.1.0"
authors = ["Sam <earthstamper@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
avior_infuser_lib = { path = "avior-infuser-rust-lib"}